#!/bin/sh
# Writes our emulator changes out as patches.
#
# The forks are where the work happens -- a branch rebases onto a moving
# upstream, a patch does not -- but they are also three repositories on
# somebody else's servers, and this project should not stop existing if
# one of them does. So the patches are generated from the forks rather
# than maintained by hand: they cannot drift, because nobody edits them.
#
# They also say plainly what this project changes in an emulator, which
# a fork does not: a fork is a whole emulator with our work somewhere
# inside it.
set -e

DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
OUT="$DIR/patches"
mkdir -p "$OUT"

# Each fork keeps an untouched copy of upstream's default branch beside
# our own, which is what the changes are measured against. Cemu calls it
# main; the other two call it master.
emulators="melonDS:origin/master azahar:origin/master Cemu:origin/main"

for pair in $emulators; do
    name=${pair%%:*}
    ref=${pair#*:}
    repo="$DIR/emulators/$name"

    if [ ! -d "$repo/.git" ]; then
        echo "$name: no checkout, skipped"
        continue
    fi

    base=$(git -C "$repo" merge-base HEAD "$ref" 2>/dev/null || true)
    if [ -z "$base" ]; then
        echo "$name: no upstream base against $ref, skipped" >&2
        continue
    fi

    upstream_url=$(git -C "$repo" config --get remote.upstream.url 2>/dev/null || echo "unknown")
    target="$OUT/$name.patch"

    {
        echo "# bottom_screen support for $name"
        echo "#"
        echo "# Generated by scripts/make_patches.sh -- do not edit by hand."
        echo "#"
        echo "# Upstream:  $upstream_url"
        echo "# Applies to: $base"
        echo "#"
        echo "# Apply to your own checkout of that commit:"
        echo "#     git -C $name apply /path/to/$name.patch"
        echo "#"
        echo "# The C sources it calls into are not in this patch. They live in"
        echo "# bottom_screen_server, which the emulator's build expects to find"
        echo "# beside it; see the README."
        echo "#"
        git -C "$repo" diff "$base" HEAD
    } > "$target"

    printf '%s: %s\n' "$name" "$(git -C "$repo" diff --shortstat "$base" HEAD)"
done

echo
echo "written to $OUT"
